version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres_db:5432/admin
    networks:
      - app_network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./dist
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
