FROM python:3.12-slim

WORKDIR /app

COPY requirements-dev.txt requirements-dev.txt

RUN pip install -r requirements-dev.txt

COPY . .

 CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]
