version: '3.8'

services:
  db:
    image: postgres:13
    container_name: test_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d test" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: test_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://test:test@db:5432/test"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
